#
# linux / installation with regular packages
#

- block:
  - name: '[PYTHON3] install python3 standard packages'
    apt:
      name: "{{ packages }}"
      update_cache: yes
      state: present
      cache_valid_time: 3600
    vars:
      packages:
        - "{{ 'python%s.%s' % (python3_version.major, python3_version.minor) }}"
        - "{{ 'libpython%s.%s-dev' % (python3_version.major, python3_version.minor) }}"

  - name: '[PYTHON3] locating python3 binary'
    shell: python3 -c "import sys; print('%d.%d\n%s' % (sys.version_info.major, sys.version_info.minor, sys.executable))"
    register: python3_output_ubuntu
    ignore_errors: False
    tags:
      - capability

  - name: '[PYTHON3] registering python3 to Bamboo capabilities'
    set_fact:
      bamboo_capabilities: "{{ (bamboo_capabilities | default({})) | combine({item.key:item.value}) }}"
    with_items:
      - key: 'system.builder.command.python{{python3_output_ubuntu.stdout_lines.0}}'
        value: '{{ python3_output_ubuntu.stdout_lines.1 }}'
    tags:
      - capability

  when: (ansible_distribution=="Ubuntu")

  tags:
    - python3
