#
# OSX / installation
#
- block:
  - name: '[PYTHON3] transfer installation package'
    copy:
      src: "{{ python3_installer.file }}"
      dest: "/tmp/{{ python3_installer.file | basename }}"

  - name: '[PYTHON3] package installation'
    shell: "installer -allowUntrusted -dumplog -pkg \"/tmp/{{ python3_installer.file | basename }}\" -target /"

  - name: '[PYTHON3] locating python3 binary'
    shell: /usr/local/bin/python3 -c "import sys; print('%d.%d\n%s' % (sys.version_info.major, sys.version_info.minor, sys.executable))"
    register: python3_output_osx
    ignore_errors: False
    tags:
      - capability

  - name: '[PYTHON3] registering python3 to Bamboo capabilities'
    set_fact:
      bamboo_capabilities: "{{ ( bamboo_capabilities | default({})) | combine({item.key:item.value}) }}"
    with_items:
      - key: 'system.builder.command.python{{python3_output_osx.stdout_lines.0}}'
        value: '{{ python3_output_osx.stdout_lines.1 }}'
    tags:
      - capability

  when: ansible_distribution == "MacOSX"

  rescue:
    - debug: msg="An error occured"
    - command: /bin/false

  tags:
    - python3
