# This file installs packages and declares associated capabilities
# For each defined package,
# - it transfers the package to the host
# - it runs a specific installation script
# - it declares the associated capabilities, if any
# - it does not cleans up the file. The file is in /tmp, so it should be safe
#   to keep it there to accelerate further transfers


- name: '[PYTHON3] Checking that required variables are set'
  fail: msg="{{ item }} is not defined"
  when: item is undefined
  with_items:
    - python3_version
    - python3_installer

#
#
# Windows
#
#

- block:

  - name: '[PYTHON3] copy the installer'
    win_copy:
      src: "{{ python3_installer.file }}"
      dest: "{{ ansible_env['TEMP'] }}\\{{python3_installer.file | basename}}"

  # installs on a default folder c:\pythonXY
  - name: '[PYTHON3] installation'
    win_package:
      path: "{{ ansible_env['TEMP'] }}\\{{python3_installer.file | basename}}"
      state: present
      creates_path: "C:\\Python{{python3_version.major}}{{python3_version.minor}}"
      arguments: InstallAllUsers=1 Include_debug=1 TargetDir="C:\\Python{{python3_version.major}}{{python3_version.minor}}"

  # replacing backslashes to forward ones
  - name: '[PYTHON3] finding the installation path'
    set_fact:
      python_binary_location: "C:\\Python{{python3_version.major}}{{python3_version.minor}}"
      
  when: ansible_os_family=="Windows"

  rescue:
    - debug: msg="An error occured"
    - command: /bin/false

  always:
    # pretty sure that this file will not get cleaned up
    - win_file:
        path: "{{ ansible_env['TEMP'] }}\\{{python3_installer.file | basename}}"
        state: absent

  tags: 
    - python3 


#
# OSX
#
- block:
  - name: '[PYTHON3] transfer installation package'
    copy:
      src: "{{ python3_installer.file }}"
      dest: "/tmp/{{ python3_installer.file | basename }}"

  - name: '[PYTHON3] package installation'
    shell: "installer -allowUntrusted -dumplog -pkg \"/tmp/{{ python3_installer.file | basename }}\" -target /"
        
  when: (ansible_distribution=="MacOSX")

  rescue:
    - debug: msg="An error occured"
    - command: /bin/false

  tags: 
    - python3 

#
# linux: installation with regular packages
#
- block:
  - name: '[PYTHON3] install python3 standard packages'
    apt: name="{{ item }}" update_cache=yes state=present cache_valid_time=3600
    with_items: 
     - "{{ 'python%s.%s' % (python3_version.major, python3_version.minor) }}"
     - "{{ 'libpython%s.%s-dev' % (python3_version.major, python3_version.minor) }}"

  when: (ansible_distribution=="Ubuntu")

  tags: 
    - python3


# locating python3 for OSX and Ubuntu for filling the capability
- block:

  - name: '[PYTHON3] locating python3 binary'
    shell: 'bash -l -c "which python3"'
    register: python3_which_output
    ignore_errors: False
    tags: 
    - capability
    
  - name: '[PYTHON3] locate'
    set_fact:
      python_binary_location="{{ python3_which_output.stdout }}"
    tags: 
    - capability
          
  when: (ansible_distribution=="MacOSX") or (ansible_distribution=="Ubuntu")
  
  rescue:
    - debug: msg="An error occured"
    - command: /bin/false

  tags: 
    - python3 


#
# REGISTER python3 into bamboo capabilities
#
- name: '[BAMBOO][PYTHON3] register python3 capability'
  set_fact:
    bamboo_capabilities: "{{ bamboo_capabilities | combine({'system.builder.command.python%s.%s' % (python3_version.major, python3_version.minor): python_binary_location }) }}"
  tags: 
  - python3
  - capability 
    